id = "macrottie.blush"
name = "blush"
description = "Simple mod to make your character blush without getting super drunk."
version = "1.0.0"
homepage = "https://github.com/mmccall0813/blush"
author = "macrottie"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./macrottie.blush/macrottie.blush.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"